### ISSUE TITLE
Did it work with Manim?

### ISSUE THREAD

**Issue by marcelo-earth** [treuille/streamlit-manim#1]
Hi @treuille, I want to run an interactive version of Manim in Streamlit. I'm trying to figure how you installed the dependencies but I can't.

Please did this work for you? Could you give me some ideas on how to run Manim on Streamlit?

🙏 Thank you in advance.

**Comment by ash2shukla** [comment]
@360macky last I checked it was working in my fork https://github.com/ash2shukla/streamlit-manim just do a docket-compose up

**Comment by marcelo-earth** [comment]
> @360macky last I checked it was working in my fork https://github.com/ash2shukla/streamlit-manim just do a docket-compose up

Wow! Thank you so much!! 🙏
